// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MusicStreamingService.Data.CompiledModels
{
    public partial class MusicStreamingContextModel
    {
        private MusicStreamingContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("74a0bda9-8e3c-4996-b538-b26e0d2c50be"), entityTypeCount: 24)
        {
        }

        partial void Initialize()
        {
            var albumEntity = AlbumEntityEntityType.Create(this);
            var albumFavoriteEntity = AlbumFavoriteEntityEntityType.Create(this);
            var allowedDistributionEntity = AllowedDistributionEntityEntityType.Create(this);
            var deviceEntity = DeviceEntityEntityType.Create(this);
            var genreEntity = GenreEntityEntityType.Create(this);
            var paymentEntity = PaymentEntityEntityType.Create(this);
            var permissionEntity = PermissionEntityEntityType.Create(this);
            var playlistEntity = PlaylistEntityEntityType.Create(this);
            var playlistFavoriteEntity = PlaylistFavoriteEntityEntityType.Create(this);
            var playlistImportStagingEntity = PlaylistImportStagingEntityEntityType.Create(this);
            var playlistImportTaskEntity = PlaylistImportTaskEntityEntityType.Create(this);
            var playlistSongEntity = PlaylistSongEntityEntityType.Create(this);
            var regionEntity = RegionEntityEntityType.Create(this);
            var roleEntity = RoleEntityEntityType.Create(this);
            var rolePermissionEntity = RolePermissionEntityEntityType.Create(this);
            var songArtistEntity = SongArtistEntityEntityType.Create(this);
            var songEntity = SongEntityEntityType.Create(this);
            var songFavoriteEntity = SongFavoriteEntityEntityType.Create(this);
            var songGenreEntity = SongGenreEntityEntityType.Create(this);
            var streamingEventEntity = StreamingEventEntityEntityType.Create(this);
            var subscriberEntity = SubscriberEntityEntityType.Create(this);
            var subscriptionEntity = SubscriptionEntityEntityType.Create(this);
            var userEntity = UserEntityEntityType.Create(this);
            var userRoleEntity = UserRoleEntityEntityType.Create(this);

            AlbumEntityEntityType.CreateForeignKey1(albumEntity, userEntity);
            AlbumEntityEntityType.CreateForeignKey2(albumEntity, userEntity);
            AlbumFavoriteEntityEntityType.CreateForeignKey1(albumFavoriteEntity, albumEntity);
            AlbumFavoriteEntityEntityType.CreateForeignKey2(albumFavoriteEntity, userEntity);
            AllowedDistributionEntityEntityType.CreateForeignKey1(allowedDistributionEntity, regionEntity);
            AllowedDistributionEntityEntityType.CreateForeignKey2(allowedDistributionEntity, songEntity);
            DeviceEntityEntityType.CreateForeignKey1(deviceEntity, userEntity);
            PaymentEntityEntityType.CreateForeignKey1(paymentEntity, userEntity);
            PaymentEntityEntityType.CreateForeignKey2(paymentEntity, subscriptionEntity);
            PlaylistEntityEntityType.CreateForeignKey1(playlistEntity, userEntity);
            PlaylistFavoriteEntityEntityType.CreateForeignKey1(playlistFavoriteEntity, playlistEntity);
            PlaylistFavoriteEntityEntityType.CreateForeignKey2(playlistFavoriteEntity, userEntity);
            PlaylistImportStagingEntityEntityType.CreateForeignKey1(playlistImportStagingEntity, playlistImportTaskEntity);
            PlaylistImportStagingEntityEntityType.CreateForeignKey2(playlistImportStagingEntity, playlistEntity);
            PlaylistImportTaskEntityEntityType.CreateForeignKey1(playlistImportTaskEntity, userEntity);
            PlaylistSongEntityEntityType.CreateForeignKey1(playlistSongEntity, playlistEntity);
            PlaylistSongEntityEntityType.CreateForeignKey2(playlistSongEntity, songEntity);
            RolePermissionEntityEntityType.CreateForeignKey1(rolePermissionEntity, permissionEntity);
            RolePermissionEntityEntityType.CreateForeignKey2(rolePermissionEntity, roleEntity);
            SongArtistEntityEntityType.CreateForeignKey1(songArtistEntity, userEntity);
            SongArtistEntityEntityType.CreateForeignKey2(songArtistEntity, songEntity);
            SongArtistEntityEntityType.CreateForeignKey3(songArtistEntity, userEntity);
            SongEntityEntityType.CreateForeignKey1(songEntity, albumEntity);
            SongFavoriteEntityEntityType.CreateForeignKey1(songFavoriteEntity, songEntity);
            SongFavoriteEntityEntityType.CreateForeignKey2(songFavoriteEntity, userEntity);
            SongGenreEntityEntityType.CreateForeignKey1(songGenreEntity, genreEntity);
            SongGenreEntityEntityType.CreateForeignKey2(songGenreEntity, songEntity);
            StreamingEventEntityEntityType.CreateForeignKey1(streamingEventEntity, deviceEntity);
            StreamingEventEntityEntityType.CreateForeignKey2(streamingEventEntity, songEntity);
            SubscriberEntityEntityType.CreateForeignKey1(subscriberEntity, userEntity);
            SubscriberEntityEntityType.CreateForeignKey2(subscriberEntity, subscriptionEntity);
            UserEntityEntityType.CreateForeignKey1(userEntity, regionEntity);
            UserRoleEntityEntityType.CreateForeignKey1(userRoleEntity, roleEntity);
            UserRoleEntityEntityType.CreateForeignKey2(userRoleEntity, userEntity);

            AlbumEntityEntityType.CreateSkipNavigation1(albumEntity, userEntity, albumFavoriteEntity);
            GenreEntityEntityType.CreateSkipNavigation1(genreEntity, songEntity, songGenreEntity);
            PermissionEntityEntityType.CreateSkipNavigation1(permissionEntity, roleEntity, rolePermissionEntity);
            PlaylistEntityEntityType.CreateSkipNavigation1(playlistEntity, userEntity, playlistFavoriteEntity);
            RegionEntityEntityType.CreateSkipNavigation1(regionEntity, songEntity, allowedDistributionEntity);
            RoleEntityEntityType.CreateSkipNavigation1(roleEntity, permissionEntity, rolePermissionEntity);
            RoleEntityEntityType.CreateSkipNavigation2(roleEntity, userEntity, userRoleEntity);
            SongEntityEntityType.CreateSkipNavigation1(songEntity, regionEntity, allowedDistributionEntity);
            SongEntityEntityType.CreateSkipNavigation2(songEntity, genreEntity, songGenreEntity);
            SongEntityEntityType.CreateSkipNavigation3(songEntity, userEntity, songFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation1(userEntity, albumEntity, albumFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation2(userEntity, playlistEntity, playlistFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation3(userEntity, songEntity, songFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation4(userEntity, roleEntity, userRoleEntity);

            AlbumEntityEntityType.CreateAnnotations(albumEntity);
            AlbumFavoriteEntityEntityType.CreateAnnotations(albumFavoriteEntity);
            AllowedDistributionEntityEntityType.CreateAnnotations(allowedDistributionEntity);
            DeviceEntityEntityType.CreateAnnotations(deviceEntity);
            GenreEntityEntityType.CreateAnnotations(genreEntity);
            PaymentEntityEntityType.CreateAnnotations(paymentEntity);
            PermissionEntityEntityType.CreateAnnotations(permissionEntity);
            PlaylistEntityEntityType.CreateAnnotations(playlistEntity);
            PlaylistFavoriteEntityEntityType.CreateAnnotations(playlistFavoriteEntity);
            PlaylistImportStagingEntityEntityType.CreateAnnotations(playlistImportStagingEntity);
            PlaylistImportTaskEntityEntityType.CreateAnnotations(playlistImportTaskEntity);
            PlaylistSongEntityEntityType.CreateAnnotations(playlistSongEntity);
            RegionEntityEntityType.CreateAnnotations(regionEntity);
            RoleEntityEntityType.CreateAnnotations(roleEntity);
            RolePermissionEntityEntityType.CreateAnnotations(rolePermissionEntity);
            SongArtistEntityEntityType.CreateAnnotations(songArtistEntity);
            SongEntityEntityType.CreateAnnotations(songEntity);
            SongFavoriteEntityEntityType.CreateAnnotations(songFavoriteEntity);
            SongGenreEntityEntityType.CreateAnnotations(songGenreEntity);
            StreamingEventEntityEntityType.CreateAnnotations(streamingEventEntity);
            SubscriberEntityEntityType.CreateAnnotations(subscriberEntity);
            SubscriptionEntityEntityType.CreateAnnotations(subscriptionEntity);
            UserEntityEntityType.CreateAnnotations(userEntity);
            UserRoleEntityEntityType.CreateAnnotations(userRoleEntity);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
