// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MusicStreamingService.Data.CompiledModels
{
    public partial class MusicStreamingContextModel
    {
        private MusicStreamingContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("22fb2063-0695-423f-af20-c9b7f789bf91"), entityTypeCount: 19)
        {
        }

        partial void Initialize()
        {
            var albumEntity = AlbumEntityEntityType.Create(this);
            var albumFavoriteEntity = AlbumFavoriteEntityEntityType.Create(this);
            var albumSongEntity = AlbumSongEntityEntityType.Create(this);
            var allowedDistributionEntity = AllowedDistributionEntityEntityType.Create(this);
            var deviceEntity = DeviceEntityEntityType.Create(this);
            var genreEntity = GenreEntityEntityType.Create(this);
            var paymentEntity = PaymentEntityEntityType.Create(this);
            var playlistEntity = PlaylistEntityEntityType.Create(this);
            var playlistFavoriteEntity = PlaylistFavoriteEntityEntityType.Create(this);
            var playlistSongEntity = PlaylistSongEntityEntityType.Create(this);
            var regionEntity = RegionEntityEntityType.Create(this);
            var songArtistEntity = SongArtistEntityEntityType.Create(this);
            var songEntity = SongEntityEntityType.Create(this);
            var songFavoriteEntity = SongFavoriteEntityEntityType.Create(this);
            var songGenreEntity = SongGenreEntityEntityType.Create(this);
            var streamingEventEntity = StreamingEventEntityEntityType.Create(this);
            var subscriberEntity = SubscriberEntityEntityType.Create(this);
            var subscriptionEntity = SubscriptionEntityEntityType.Create(this);
            var userEntity = UserEntityEntityType.Create(this);

            AlbumEntityEntityType.CreateForeignKey1(albumEntity, userEntity);
            AlbumEntityEntityType.CreateForeignKey2(albumEntity, userEntity);
            AlbumFavoriteEntityEntityType.CreateForeignKey1(albumFavoriteEntity, albumEntity);
            AlbumFavoriteEntityEntityType.CreateForeignKey2(albumFavoriteEntity, userEntity);
            AlbumSongEntityEntityType.CreateForeignKey1(albumSongEntity, albumEntity);
            AlbumSongEntityEntityType.CreateForeignKey2(albumSongEntity, songEntity);
            AllowedDistributionEntityEntityType.CreateForeignKey1(allowedDistributionEntity, regionEntity);
            AllowedDistributionEntityEntityType.CreateForeignKey2(allowedDistributionEntity, songEntity);
            DeviceEntityEntityType.CreateForeignKey1(deviceEntity, userEntity);
            PaymentEntityEntityType.CreateForeignKey1(paymentEntity, userEntity);
            PaymentEntityEntityType.CreateForeignKey2(paymentEntity, subscriptionEntity);
            PlaylistEntityEntityType.CreateForeignKey1(playlistEntity, userEntity);
            PlaylistEntityEntityType.CreateForeignKey2(playlistEntity, userEntity);
            PlaylistFavoriteEntityEntityType.CreateForeignKey1(playlistFavoriteEntity, playlistEntity);
            PlaylistFavoriteEntityEntityType.CreateForeignKey2(playlistFavoriteEntity, userEntity);
            PlaylistSongEntityEntityType.CreateForeignKey1(playlistSongEntity, playlistEntity);
            PlaylistSongEntityEntityType.CreateForeignKey2(playlistSongEntity, songEntity);
            SongArtistEntityEntityType.CreateForeignKey1(songArtistEntity, userEntity);
            SongArtistEntityEntityType.CreateForeignKey2(songArtistEntity, songEntity);
            SongArtistEntityEntityType.CreateForeignKey3(songArtistEntity, userEntity);
            SongFavoriteEntityEntityType.CreateForeignKey1(songFavoriteEntity, songEntity);
            SongFavoriteEntityEntityType.CreateForeignKey2(songFavoriteEntity, userEntity);
            SongGenreEntityEntityType.CreateForeignKey1(songGenreEntity, genreEntity);
            SongGenreEntityEntityType.CreateForeignKey2(songGenreEntity, songEntity);
            StreamingEventEntityEntityType.CreateForeignKey1(streamingEventEntity, deviceEntity);
            StreamingEventEntityEntityType.CreateForeignKey2(streamingEventEntity, songEntity);
            SubscriberEntityEntityType.CreateForeignKey1(subscriberEntity, userEntity);
            SubscriberEntityEntityType.CreateForeignKey2(subscriberEntity, subscriptionEntity);
            UserEntityEntityType.CreateForeignKey1(userEntity, regionEntity);

            AlbumEntityEntityType.CreateSkipNavigation1(albumEntity, userEntity, albumFavoriteEntity);
            GenreEntityEntityType.CreateSkipNavigation1(genreEntity, songEntity, songGenreEntity);
            PlaylistEntityEntityType.CreateSkipNavigation1(playlistEntity, userEntity, playlistFavoriteEntity);
            RegionEntityEntityType.CreateSkipNavigation1(regionEntity, songEntity, allowedDistributionEntity);
            SongEntityEntityType.CreateSkipNavigation1(songEntity, regionEntity, allowedDistributionEntity);
            SongEntityEntityType.CreateSkipNavigation2(songEntity, genreEntity, songGenreEntity);
            SongEntityEntityType.CreateSkipNavigation3(songEntity, userEntity, songFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation1(userEntity, albumEntity, albumFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation2(userEntity, playlistEntity, playlistFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation3(userEntity, songEntity, songFavoriteEntity);

            AlbumEntityEntityType.CreateAnnotations(albumEntity);
            AlbumFavoriteEntityEntityType.CreateAnnotations(albumFavoriteEntity);
            AlbumSongEntityEntityType.CreateAnnotations(albumSongEntity);
            AllowedDistributionEntityEntityType.CreateAnnotations(allowedDistributionEntity);
            DeviceEntityEntityType.CreateAnnotations(deviceEntity);
            GenreEntityEntityType.CreateAnnotations(genreEntity);
            PaymentEntityEntityType.CreateAnnotations(paymentEntity);
            PlaylistEntityEntityType.CreateAnnotations(playlistEntity);
            PlaylistFavoriteEntityEntityType.CreateAnnotations(playlistFavoriteEntity);
            PlaylistSongEntityEntityType.CreateAnnotations(playlistSongEntity);
            RegionEntityEntityType.CreateAnnotations(regionEntity);
            SongArtistEntityEntityType.CreateAnnotations(songArtistEntity);
            SongEntityEntityType.CreateAnnotations(songEntity);
            SongFavoriteEntityEntityType.CreateAnnotations(songFavoriteEntity);
            SongGenreEntityEntityType.CreateAnnotations(songGenreEntity);
            StreamingEventEntityEntityType.CreateAnnotations(streamingEventEntity);
            SubscriberEntityEntityType.CreateAnnotations(subscriberEntity);
            SubscriptionEntityEntityType.CreateAnnotations(subscriptionEntity);
            UserEntityEntityType.CreateAnnotations(userEntity);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
