// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MusicStreamingService.Data.CompiledModels
{
    public partial class MusicStreamingContextModel
    {
        private MusicStreamingContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("8e193d48-c8f4-4d27-b2e3-fb2a5ee8b6cc"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var albumEntity = AlbumEntityEntityType.Create(this);
            var albumFavoriteEntity = AlbumFavoriteEntityEntityType.Create(this);
            var regionEntity = RegionEntityEntityType.Create(this);
            var userEntity = UserEntityEntityType.Create(this);

            AlbumEntityEntityType.CreateForeignKey1(albumEntity, userEntity);
            AlbumFavoriteEntityEntityType.CreateForeignKey1(albumFavoriteEntity, albumEntity);
            AlbumFavoriteEntityEntityType.CreateForeignKey2(albumFavoriteEntity, userEntity);
            UserEntityEntityType.CreateForeignKey1(userEntity, regionEntity);

            AlbumEntityEntityType.CreateSkipNavigation1(albumEntity, userEntity, albumFavoriteEntity);
            UserEntityEntityType.CreateSkipNavigation1(userEntity, albumEntity, albumFavoriteEntity);

            AlbumEntityEntityType.CreateAnnotations(albumEntity);
            AlbumFavoriteEntityEntityType.CreateAnnotations(albumFavoriteEntity);
            RegionEntityEntityType.CreateAnnotations(regionEntity);
            UserEntityEntityType.CreateAnnotations(userEntity);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
