// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using MusicStreamingService.Data;
using MusicStreamingService.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MusicStreamingContext), typeof(MusicStreamingContextModel))]
